### ISSUE TITLE
Something went wrong | Sequence contains more than one matching element

### ISSUE THREAD

**Issue by Myke500** [x42protocol/x42#1]
> Something went wrong | Sequence contains more than one matching element
Affects some users after install

Wallet sign in will load
After login user will receive an error that returns after closing the pop up dialog 
**"Something went wrong | Sequence contains more than one matching element"**

To correct the error this requires the user to delete everything in /x42node/x42/x42main/ (except wallet file) and resync the blockchain from scratch.

Afterwards it will load and run as intended.

**Comment by DennisAMenace** [comment]
Posted in wrong section, this is the x42 repo. I think you meant to put this issue into X42-FullNode-UI repo.
